### ISSUE TITLE
test_catalog_subs pokes live vizier in several places

### ISSUE THREAD

**Issue by jchate6** [LCOGT/neoexchange#566]
All tests are in `photometrics.tests.test_catalog_subs.ZeropointUnitTest`
Specifically, 
`test_call_with_diff_test_cat_force_to_UCAC4`
`test_get_cat_ra_dec_empty_list_PPMXL`
`test_get_cat_ra_dec_empty_list_UCAC4`
all fail at the moment due to timeout issues. 

I'm not sure what this means for our live production, but the tests shouldn't be hitting anything external.

**Comment by talister** [comment]
Also we have no intention of using those catalogs any more now we have Gaia DRs. The more valuable things to test would be failover in the case of non-available Simbad servers but not sure how to do that in a test as you would need to mock whatever low-level things happen in astroquery. Suggest we disable these tests for now and move on since those code paths are never being used.

**Comment by jchate6** [comment]
sounds like an easy fix.

**Comment by talister** [comment]
> sounds like an easy fix.

`@skipIf(True)`...
